add security
VavilovNikita/Notebook6 pull request #6
Opened 2023-08-08 21:59 UTC by VavilovNikita

2023-08-09 09:19 UTC, zor07 requested changes

2023-08-09 09:19 UTC, zor07 commented on src/main/resources/templates/notebook/indexByIdPage.html
> +                function myFunction(id) {
Переименуй функцию

2023-08-09 09:19 UTC, zor07 commented on src/main/resources/templates/notebook/creationPage.html
> +<!--    <br/>-->
Удали, если это не нужно

2023-08-09 09:19 UTC, zor07 commented on src/main/java/ru/vavilov/notebook6/service/NotebookService.java
> +    public Person getAuthPerson() {
Это надо вынести в отдельный сервис, типа AuthService с одним публичным методом getAuthPerson(), и инжектить этот сервис куда нужно

2023-08-09 09:19 UTC, zor07 commented on src/main/java/ru/vavilov/notebook6/service/PersonDetailsService.java
> +    PersonRepository personRepository;
private final

2023-08-09 09:19 UTC, zor07 commented on src/main/java/ru/vavilov/notebook6/security/PersonDetails.java
> +    Person person;
private final

2023-08-09 09:19 UTC, zor07 commented on src/main/java/ru/vavilov/notebook6/controller/RegisterConroller.java
>      PersonService personService;
private final

2023-08-09 09:19 UTC, zor07 commented on src/main/java/ru/vavilov/notebook6/controller/NotebookController.java
> +    @GetMapping("/allNotes")
Тут нужно переделать. 
для всех записей
урл: /notebooks 
название метода: getNotebooks

для пользовательских записей
урл: /notebooks/{personId} либо /personNotebooks если у тебя на фронте нет personId
название метода: gePersontNotebooks

Названия html тоже переделать. 
Для всех записей notebooks.html
Для пользовательских personNotebooks.html

Если они мало чем отличаются, то можно оставить вообще один notebooks.html
И средствами thymeleaf выводить разную инфу на нем

2023-08-09 09:19 UTC, zor07 commented on src/main/resources/templates/person/detailsPage.html
> +            <td><label for="password">Пароль: </label>
Даже админ не должен видеть пароль пользователя. Пароль должен знать только пользователь, и в базе он хранится зашифрованным (должен по крайней мере)

2023-08-09 09:19 UTC, zor07 commented on src/main/java/ru/vavilov/notebook6/service/NotebookService.java
>          notebook.setCreatedAt(new Date());
Старайся не использовать класс Date для работы с датами. Используй классы из datetime API которые появились в Java 8. Например тут Instant.now(). Посмотри на классы LocalDate, LocalDateTime, Instant

2023-08-09 09:19 UTC, zor07 commented on src/main/java/ru/vavilov/notebook6/service/PersonDetailsService.java
> +        Optional<Person> person = personRepository.findByUsername(username);
```
return personRepository.findByUsername(username)
     .map(person -> new PersonDetails(person))
     .orElseThrow(() -> new UsernameNotFoundException("Не удается найти пользователя :" + username))
```

2023-08-12 12:41 UTC, VavilovNikita commented on src/main/java/ru/vavilov/notebook6/service/PersonDetailsService.java
> +    PersonRepository personRepository;
ok

2023-08-12 12:43 UTC, VavilovNikita commented on src/main/java/ru/vavilov/notebook6/security/PersonDetails.java
> +    Person person;
ok

2023-08-12 12:43 UTC, VavilovNikita commented on src/main/java/ru/vavilov/notebook6/controller/RegisterConroller.java
>      PersonService personService;
ok

2023-08-12 12:50 UTC, VavilovNikita commented on src/main/resources/templates/person/detailsPage.html
> +            <td><label for="password">Пароль: </label>
ok

2023-08-12 12:58 UTC, VavilovNikita commented on src/main/java/ru/vavilov/notebook6/service/PersonDetailsService.java
> +        Optional<Person> person = personRepository.findByUsername(username);
ok

2023-08-12 13:17 UTC, zor07 requested changes

2023-08-12 13:17 UTC, zor07 commented on src/main/java/ru/vavilov/notebook6/service/AuthService.java
> +    UserRepository userRepository;
private final

2023-08-12 13:17 UTC, zor07 commented on src/main/java/ru/vavilov/notebook6/util/UserValidator.java
> +    UserService userService;
private final

2023-08-12 13:36 UTC, VavilovNikita commented on src/main/java/ru/vavilov/notebook6/service/AuthService.java
> +    UserRepository userRepository;
ok

2023-08-12 13:36 UTC, VavilovNikita commented on src/main/java/ru/vavilov/notebook6/util/UserValidator.java
> +    UserService userService;
ok

2023-08-12 13:37 UTC, merged